config/routes.rb
Vinyls::Application.routes.draw do

  

  resources :selections

  root :to => 'selections#index'

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  get '/albums/new' => 'albums#new', as: 'new_album'
  get '/join' => 'clearance/users#new', as: 'join'
  delete '/sign_out' => 'clearance/sessions#destroy', as:'sign_out'
  get "/:username", to: "users#show", as: "user"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == "admin"
      can :manage, :all
    else
      can :read, :all
      can :create, Selection
      can :update, Selection do |selection|
        selection.try(:user) == user
      end
      can :destroy, Selection do |selection|
        selection.try(:user) == user
      end
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base

  S3_CREDENTIALS = { :access_key_id => ENV['S3_KEY'], :secret_access_key => ENV['S3_SECRET'], :bucket => "vinyls-app"}

  attr_accessible :title, :artist, :genre, :album_art

  has_many :selections
  has_many :users, through: :selections
  
  has_attached_file :album_art, :styles => { 
    medium: "300x300!", 
    small: "150x150>",
    thumb: "80x80#" }, 
    dependent: :destroy,
    storage: :s3, 
    s3_credentials: S3_CREDENTIALS,
    s3_host_name: "s3-eu-west-1.amazonaws.com",
    path: ":hash",
    hash_secret: "492091f930411ba79c07d4e434226267f55f4626b3603e9f912539c03a750888bbec9ddf046b550efea9f74cfe3fa9ed8fd4ab87ce5b1378250fd89f8c704fb1"

  validates_presence_of :title, :artist
  validates_attachment_size :album_art, :less_than => 10.megabytes

  belongs_to :user
  validates_associated :user, :message => "Can't add more than 9 releases. Remove one?"
  
  delegate :email, :to => :user, :prefix => true

end

app/models/selection.rb
class Selection < ActiveRecord::Base

  attr_accessible :description, :album

  belongs_to :user
  belongs_to :album

end

app/models/user.rb
class User < ActiveRecord::Base

  include Clearance::User

  attr_accessible :username, :remember_token
  validates_format_of :username, with: /\A[a-z0-9_-]{2,19}\Z/i

  validate :limit_selection_count

  has_many :selections, limit: 16
  has_many :albums, through: :selections, order: 'created_at DESC'

  def limit_selection_count
    errors.add(:selections, "Too many selections") if selections.count > 16
  end

  def to_param
    username
  end

end

app/models/vinyl.rb
class Vinyl < ActiveRecord::Base

  attr_accessible :title, :artist, :genre, :thoughts, :album_art
  
  has_attached_file :album_art, :styles => { 
    medium: "300x300!", 
    small: "150x150>",
    thumb: "250x250#" }, 
    dependent: :destroy,
    storage: :s3, 
    s3_credentials: S3_CREDENTIALS,
    s3_host_name: "s3-eu-west-1.amazonaws.com",
    path: ":hash",
    hash_secret: "492091f930411ba79c07d4e434226267f55f4626b3603e9f912539c03a750888bbec9ddf046b550efea9f74cfe3fa9ed8fd4ab87ce5b1378250fd89f8c704fb1"

  validates_presence_of :title, :artist, :thoughts
  validates_attachment_size :album_art, :less_than => 10.megabytes

  belongs_to :user
  validates_associated :user, :message => "Can't add more than 9 releases. Remove one?"
  
  delegate :email, :to => :user, :prefix => true

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  protect_from_forgery

end

app/controllers/selections_controller.rb
require './lib/last_fm'
require './lib/album_selection_services'
class SelectionsController < ApplicationController

  load_and_authorize_resource

  def index
    @selections = Selection.all(order: "created_at DESC", limit: 50)
  end

  def new
  end

  def create
    artist = params[:artist]
    title = params[:title]
    begin
      @selection = AlbumSelectionServices.select_album(current_user, artist, title)
      redirect_to current_user, flash: { notice: "Selection added" }
    rescue AlbumNotFoundException
      redirect_to new_selection_path, :flash => { error: "Album not found on Last.fm." }
    rescue AlbumArtNotFoundException
      redirect_to new_selection_path, :flash => { error: "Album art not found on Last.fm" }
    end
  end

  def show # GET /album/[:id]
  end

  def edit 
    authorize! :update, @selection
  end

  def update
    @selection.update_attributes(description: params[:description])
    if @selection.update_attributes(params[:selection])
      redirect_to @selection, notice: 'Selection was successfully updated.'
    else
      render :edit, notice: 'Selection was not updated.'
    end
  end

  def destroy
    @selection.destroy

    redirect_to current_user, flash: { notice: "Selection removed" }
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def show
    @user = User.find_by_username(params[:username])
    @selections = @user.selections.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<% if current_user %>
  <% if current_user.albums.count < 9 %>
    <div class="add-album">
      <%= link_to '', new_album_path %>
    </div>
  <% end %>
<% else %>
  <div class="add-album">
    <%= link_to '', sign_up_path, class: "add-album" %>
  </div>
<% end %>


<% @albums.each do |album| %>
  <%= link_to album, class: "album-container" do %>
    <ul class="album-list">
      <li class="artist"><%= album.artist %></li>
      <li class="title"><%= album.title %></li>
    </ul>
    <%= image_tag album.album_art.url(:medium), class: "album-art" %>
  <% end %>
<% end %>

app/views/albums/new.html.erb
<%= form_for @album do |form| %>
  <% @album.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
  <fieldset><%= form.label :artist, :required => true %>
    <%= form.text_field :artist %></fieldset>
  <fieldset><%= form.label :title %>
    <%= form.text_field :title, :required => true %></fieldset>
  <fieldset><%= form.label :thoughts, :required => true %>
    <%= form.text_area :thoughts %></fieldset>
  <fieldset><%= form.label :album_art %>
    <%= form.file_field :album_art %></fieldset>
  <%= form.submit 'Add a Record', class: 'button' %>
<% end %>

app/views/albums/show.html.erb
<p class="notice"><%= notice %></p>

<%= link_to 'Back to List', root_path, class: "button" %>

<ul class="single-album-list">
  <li class="artist"><%= @album.artist %></li>
  <li class="title"><%= @album.title %></li>
  <li class="username"><%= link_to @album.user.username, @album.user %></li>
  <li class="thoughts"><%= @album.thoughts %></li>
  <li><%= image_tag @album.album_art.url %></li>
</ul>

<% if current_user %>
  <% if current_user.id == @album.user_id %>
    <ul class="edit-links">
      <li><%= link_to "Edit", edit_album_path, class: "button secondary" %></li>
      <li><%= link_to 'Destroy', { action: :destroy, id: @album.id }, method: :delete, data: { confirm: 'Are you sure?' }, class: "button caution" %></li>
    </ul>
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Vinyls
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = favicon_link_tag
    = csrf_meta_tags
    %meta{:content => "One profile, eight albums. Select  your top eight albums of all time and tell the world what they mean to you. Meet others with a similar taste in music to you and form discussions around the albums you both enjoy.", :name => "description"}/
    <script type="text/javascript" src="//use.typekit.net/knl3rrp.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  %body


    #container

      %header
        = link_to "Vinyls", root_path, id: "logo"
        %nav
          %ul
            - if signed_in?   
              - if current_user.selections.count < 8
                %li
                  = link_to user_path(current_user) do
                    My Profile
                %li
                  = link_to new_selection_path do
                    New Selection
            - if signed_in?          

              %li
                = link_to sign_out_path, method: "delete" do
                  Sign Out

            - else
              %li
                = link_to sign_in_path do
                  Sign In
              %li
                = link_to join_path do
                  Join Vinyls
      .notice= flash[:notice]
      .error= flash[:error]
      / .sidebar  
      /   %ul
      .main-wrapper
        = yield

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40230818-1', 'herokuapp.com');
      ga('send', 'pageview');

app/views/selections/create.html.erb
<h1>Selection Logged!</h1>

<div class='username-header'>Selected by <%= link_to @selection.user.username, @selection.user %></div>

<ul class='single-album-list'>
  <li class="artist"><%= @selection.album.artist %></li>
  <li class="title"><%= @selection.album.title %></li>
  <li><%= image_tag @selection.album.album_art.url %></li>  
  <% if @selection.description %>
    <li class="description"><%= @selection.description %></li>
  <% end %>
</ul>

app/views/selections/edit.html.erb
<div class="form-wrapper">
  <%= form_tag selection_path, method: 'put' do %>
      
    <%= label_tag :description %>
    <%= text_area_tag :description %>
    <%= submit_tag "Edit Record", class: 'button' %>

  <% end %>
</div>

app/views/selections/index.html.erb
<ul class="selections">
  <% @selections.each do |selection| %>
    <li class="selection">
      <%= link_to selection do %>
        <div class="selection-album-details">
          <div class="selection-album-artist"><%= selection.album.artist %></div>
          <div class="selection-album-title"><%= selection.album.title %></div>
        </div>
        <%= image_tag selection.album.album_art.url(:thumb), class: "selection-album-thumb" %>

      <% end %>
    </li>
  <% end %>
</ul>

app/views/selections/new.html.erb
<div class="form-wrapper">

  <%= form_tag selections_path, method: 'post' do %>

  <fieldset>
    <%= label_tag :artist %>
    <%= text_field_tag :artist %>
  </fieldset>
  <fieldset>
    <%= label_tag :title %>
    <%= text_field_tag :title %>
  </fieldset>
  <fieldset>
    <%= label_tag :description %>
    <%= text_area_tag :description %>
  </fieldset>
    <%= submit_tag "Add a Record from Last.fm", class: 'button' %>

  <% end %>

  <%= link_to "Add Custom Album", new_album_path %>
</div>

app/views/selections/show.html.erb
<div class="selection-art">
  <%= image_tag @selection.album.album_art.url(:medium) %> 
</div>

<div class="selection-info">
  <div class='username-header'>Selected by <%= link_to @selection.user.username, @selection.user %></div>
  <ul>
    <li class="selection-artist"><%= @selection.album.artist %></li>
    <li class="selection-title"><%= @selection.album.title %></li>
    <% if @selection.description %>
      <li class="selection-description"><%= @selection.description %></li>
    <% end %>
  </ul>
</div>

<nav class="secondary">
  <ul>
    <% if can? :update, @selection %>
      <li><%= link_to "Edit", edit_selection_path %></li>
    <% end %>
    <% if can? :destroy, @selection %>
      <li><%= link_to 'Remove', { action: :destroy, id: @selection.id }, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
      <li><%= link_to 'Back to List', root_path %></li>
  </ul>
</nav>

app/views/users/edit.html.erb
<p class="notice"><%= notice %></p>
<div class="form-wrapper">
  <%= form_for @user do |form| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :username %><br/>
      <%= form.text_field :username %><br/>
    </p>
    <p>
      <%= form.label :email %><br/>
      <%= form.text_field :email %><br/>
    </p>
    <p>
      <%= form.label :password %><be/>
      <%= form.password_field :password %><br/>
    </p>
    <p>
      <%= form.label :password_confirmation %><br/>
      <%= form.password_field :password_confirmation %><br/>
    </p>
    <%= form.submit 'Update Account', class: 'button' %>
  <% end %>
</div>


<%= link_to "Back to Users", users_path, class: "back-to-main" %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user, class: "user-container" do %>
    <ul class="user-list">
      <li class="email"><%= user.email %></li>
    </ul>
  <% end %>
<% end %>

app/views/users/new.html.erb
<p class="notice"><%= notice %></p>
<div class="form-wrapper">
  <h1>Join Vinyls</h1>
  <%= form_for @user do |form| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <%= form.label :username %>
      <%= form.text_field :username %>

      <%= form.label :email %>
      <%= form.text_field :email %>

      <%= form.label :password %>
      <%= form.password_field :password %>
    <%= form.submit 'Join Vinyls', class: 'button' %>
  <% end %>
</div>

app/views/users/show.html.erb
<ul class="selections">
  <% @selections.each do |selection| %>
    <li class="selection">
      <%= link_to selection do %>
        <div class="selection-album-details">
          <div class="selection-album-artist"><%= selection.album.artist %></div>
          <div class="selection-album-title"><%= selection.album.title %></div>
        </div>
        <%= image_tag selection.album.album_art.url(:thumb), class: "selection-album-thumb" %>

      <% end %>
    </li>
  <% end %>
</ul>

app/views/vinyls/edit.html.erb
<%= form_for @vinyl, html: { multipart: true } do |form| %>

  <fieldset><%= form.label :title %>
    <%= form.text_field :title %></fieldset>
  <fieldset><%= form.label :artist %>
    <%= form.text_field :artist %></fieldset>
  <fieldset><%= form.label :genre%>
    <%= form.text_field :genre %></fieldset>
  <fieldset><%= form.label :thoughts%>
    <%= form.text_area :thoughts %></fieldset>
  <fieldset><%= form.label :album_art %>
    <%= form.file_field :album_art %></fieldset>
  <%= form.submit 'Edit Record', class: "button" %>
<% end %>

<%= link_to "Back to Main", vinyls_path, class: "back-to-main" %>

app/views/vinyls/new.html.erb
<%= form_for @vinyl do |form| %>

  <% @vinyl.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>

  <fieldset><%= form.label :title %>
    <%= form.text_field :title, :required => true %></fieldset>
  <fieldset><%= form.label :artist, :required => true %>
    <%= form.text_field :artist %></fieldset>
  <fieldset><%= form.label :thoughts, :required => true %>
    <%= form.text_area :thoughts %></fieldset>
  <fieldset><%= form.label :album_art %>
    <%= form.file_field :album_art %></fieldset>
  <%= form.submit 'Add a Record', class: 'button' %>
<% end %>